name: idds-client
dependencies:
- python==3.6
- pip
- pip:
  - requests                         # requests
  - urllib3                          # url connections
  - tabulate
  - argcomplete
  - idds-common==0.11.5
  - idds-workflow==0.11.5
